### PR TITLE
feat: change app name

### LINKED ISSUE #28: Remove .lock files
Remove .lock files in project files from the project

### LINKED ISSUE #38: Change Application Name
The name of the app on devices should be changed from `op_mo_app` to `OctopOS Prime`.

### PR DESCRIPTION
**Pull request by samiigll**
I renamed the app to "OctopOS Prime".
yarn.lock file removed
closes #28 #39

### CODE REVIEW

**Comment by Maraza25** [comment]
Please add the statement `closes #28 #39` in the comment section to close these issues

**Review by Maraza25 — APPROVED** [review]

**Comment by doganabdussamed** [comment]
.

**Comment by doganabdussamed** [comment]
.

**Review by doganabdussamed — COMMENTED** [review]
.

**Review by doganabdussamed — APPROVED** [review]
.

**Pull request merged**
