### PR TITLE
Refactor: Replace all references from 'Register' to 'Sign Up'

### LINKED ISSUE #49: Updating Register References to 'Sign Up'
All references to 'Register' in the project must be changed to 'Sign Up'. This change will be applied from UI text, file names, function names and all related places in the code.

### PR DESCRIPTION
**Pull request by nedimtoymus**
This pull request addresses issue #49. All references to 'Register' have been replaced with 'Sign Up' across the project. 
closes #49 

Please review the changes and merge if everything looks good.

### CODE REVIEW

**Review by Maraza25 — CHANGES_REQUESTED** [review]
Please remove the Turkish comment lines and do not delete the previously added comment lines

**Review by Maraza25 — APPROVED** [review]

**Review by doganabdussamed — APPROVED** [review]
.

**Comment by doganabdussamed** [comment]
.

**Comment by doganabdussamed** [comment]
.

**Review by samiigll — APPROVED** [review]

**Pull request merged**
